var cityData=[
	{
		province:{name:"热门城市"},
		city:[
			{name:"北京",href:"#"},
			{name:"宁波",href:"#"},
			{name:"深圳",href:"#"},
			{name:"厦门",href:"#"},
			{name:"成都",href:"#"}
		]
	},
	{
		province:{name:"北京",href:"#"},
		city:[]
	},
	{
		province:{name:"新疆",href:"#"},
		city:[
			{name:"乌鲁木齐",href:"#"}
		]
	},
	{
		province:{name:"辽宁",href:"#"},
		city:[
			{name:"沈阳",href:"#"},
			{name:"大连",href:"#"},
			{name:"抚顺",href:"#"},
			{name:"盘锦",href:"#"},
			{name:"鞍山",href:"#"}
		]
	},
	{
		province:{name:"湖南",href:"#"},
		city:[
			{name:"长沙",href:"#"},
			{name:"湘潭",href:"#"}
		]
	},
	{
		province:{name:"河北",href:"#"},
		city:[
			{name:"石家庄",href:"#"},
			{name:"唐山",href:"#"},
			{name:"保定",href:"#"},
			{name:"沧州",href:"#"},
			{name:"秦皇岛",href:"#"},
			{name:"廊坊",href:"#"},
			{name:"邯郸",href:"#"}
		]
	},
	{
		province:{name:"内蒙古",href:"#"},
		city:[
			{name:"呼和浩特",href:"#"},
			{name:"包头",href:"#"}
		]
	},
	{
		province:{name:"天津",href:"#"},
		city:[]
	},
	{
		province:{name:"福建",href:"#"},
		city:[
			{name:"福州",href:"#"},
			{name:"厦门",href:"#"},
			{name:"泉州",href:"#"},
			{name:"漳州",href:"#"},
			{name:"宁德",href:"#"},
			{name:"龙岩",href:"#"}
		]
	},
	{
		province:{name:"陕西",href:"#"},
		city:[
			{name:"西安",href:"#"},
			{name:"咸阳",href:"#"}
		]
	},
	{
		province:{name:"浙江",href:"#"},
		city:[
			{name:"杭州",href:"#"},
			{name:"宁波",href:"#"},
			{name:"台州",href:"#"},
			{name:"温州",href:"#"},
			{name:"绍兴",href:"#"},
			{name:"金华",href:"#"}
		]
	},
	{
		province:{name:"四川",href:"#"},
		city:[
			{name:"成都",href:"#"},
			{name:"绵阳",href:"#"}
		]
	},
	{
		province:{name:"贵州",href:"#"},
		city:[
			{name:"贵阳",href:"#"},
			{name:"遵义",href:"#"}
		]
	},
	{
		province:{name:"云南",href:"#"},
		city:[
			{name:"昆明",href:"#"}
		]
	},
	{
		province:{name:"上海",href:"#"},
		city:[]
	},
	{
		province:{name:"山西",href:"#"},
		city:[
			{name:"太原",href:"#"},
			{name:"晋城",href:"#"},
			{name:"大同",href:"#"},
			{name:"临汾",href:"#"}
		]
	},
	{
		province:{name:"江西",href:"#"},
		city:[
			{name:"南昌",href:"#"},
			{name:"九江",href:"#"},
			{name:"抚州",href:"#"},
			{name:"赣州",href:"#"}
		]
	},
	{
		province:{name:"广西",href:"#"},
		city:[
			{name:"南宁",href:"#"},
			{name:"柳州",href:"#"},
			{name:"桂林",href:"#"}
		]
	},
	{
		province:{name:"黑龙江",href:"#"},
		city:[
			{name:"哈尔滨",href:"#"},
			{name:"大庆",href:"#"}
		]
	},
	{
		province:{name:"宁夏",href:"#"},
		city:[
			{name:"银川",href:"#"}
		]
	},
	{
		province:{name:"江苏",href:"#"},
		city:[
			{name:"南京",href:"#"},
			{name:"盐城",href:"#"},
			{name:"徐州",href:"#"},
			{name:"宿迁",href:"#"},
			{name:"泰州",href:"#"},
			{name:"连云港",href:"#"},
			{name:"无锡",href:"#"},
			{name:"常州",href:"#"},
			{name:"扬州",href:"#"},
			{name:"苏州",href:"#"},
			{name:"镇江",href:"#"},
			{name:"淮安",href:"#"},
			{name:"南通",href:"#"}
		]
	},
	{
		province:{name:"安徽",href:"#"},
		city:[
			{name:"合肥",href:"#"},
			{name:" 蚌埠",href:"#"},
			{name:"淮南",href:"#"},
			{name:"芜湖",href:"#"},
			{name:"六安",href:"#"}
		]
	},
	{
		province:{name:"吉林",href:"#"},
		city:[
			{name:"长春",href:"#"},
			{name:"吉林",href:"#"}
		]
	},
	{
		province:{name:"湖北",href:"#"},
		city:[
			{name:"武汉",href:"#"},
			{name:"荆州",href:"#"},
			{name:"随州",href:"#"},
			{name:"宜昌",href:"#"},
			{name:"黄冈",href:"#"}
		]
	},
	{
		province:{name:"重庆",href:"#"},
		city:[]
	},
	{
		province:{name:"山东",href:"#"},
		city:[
			{name:"济南",href:"#"},
			{name:"威海",href:"#"},
			{name:"烟台",href:"#"},
			{name:"济宁",href:"#"},
			{name:"枣庄",href:"#"},
			{name:"临沂",href:"#"},
			{name:"潍坊",href:"#"},
			{name:"日照",href:"#"},
			{name:"青岛",href:"#"},
			{name:"淄博",href:"#"}
		]
	},
	{
		province:{name:"河南",href:"#"},
		city:[
			{name:"郑州",href:"#"},
			{name:"安阳",href:"#"},
			{name:"新乡",href:"#"},
			{name:"洛阳",href:"#"},
			{name:"焦作",href:"#"},
			{name:"开封",href:"#"},
			{name:"商丘",href:"#"},
			{name:"许昌",href:"#"}
		]
	},
	{
		province:{name:"广东",href:"#"},
		city:[
			{name:"广州",href:"#"},
			{name:"东莞",href:"#"},
			{name:"深圳",href:"#"},
			{name:"佛山",href:"#"}
		]
	}
];

var cityFragment=document.createDocumentFragment();
cityData.forEach(function(item,index){
	var cont=createCity(item,index);
	item.city.forEach(function(_item){
		cont.appendChild(getA(_item.name,_item.href));
	});
	cityFragment.appendChild(cont);
});
document.getElementById("city-wrap").appendChild(cityFragment);

// 创建class=city-item的div，并将h3标签放入div
function createCity(item,index){
	var div=dc("div");
	div.className="city-item";
	div.appendChild(getH3(item,index));
	return div;
}
// 创建效果：<h3><a href=""></a></h3>
function getH3(item,index){
	var h3=dc("h3");
	h3.appendChild([document.createTextNode(item.province.name),getA(item.province.name,item.province.href)][+(index!==0)]);
	return h3;
}

/*
	创建包含h3的div
	@ele 元素名
	@item 对象，包含province和city
	@index item的index
 */
function getEle(item,index){
	// h3
	var ele=dc("h3");
	ele.appendChild([document.createTextNode(item.province.name),getA(item.province.name,item.province.href)][+(index!==0)]);
	// div
	var div=dc("div");
	div.className=["hot-city","city-item"][+(index!==0)];
	div.appendChild(ele);
}